name: myci-test

# 触发事件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test: #job1: Setup => Checkout => Test
    name: Test
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go env
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run:  go test -v  -cover ./...